export const DASHBOARD_ACTIONS = {
    GET_BENEFICIARIES_NOTES: "GET_BENEFICIARIES_NOTES",
    CREATE_BENEFICIARIES_NOTES: "CREATE_BENEFICIARIES_NOTES",
    GET_BENEFICIARIES_PROVISION: "GET_BENEFICIARIES_PROVISION",
    CREATE_BENEFICIARIES_PROVISION: "CREATE_BENEFICIARIES_PROVISION",
    GET_FIDUCUARIES: "GET_FIDUCUARIES",
    CREATE_FIDUCUARIES: "CREATE_FIDUCUARIES",
    DELETE_FIDUCARIES: "DELETE_FIDUCARIES",
    EDIT_FIDUCARIES: "EDIT_FIDUCARIES",
    SET_LOADING: "SET_LOADING"
}

export const DASHBOARD_ENDPOINTS = {
    BENEFICIARIES_NOTES: "client/beneficiaries/note",
    BENEFICIARIES_PROVISION: "client/beneficiaries/provision",
    FIDUCUARIES: "client/fiduciary",
    DELETE_FIDUCARIES: "client/fiduciary/delete",
    EDIT_FIDUCARIES: "client/fiduciary/edit",
}